sudo: required
node_js: "8"

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

  - os: linux
    language: node_js

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

before_install:
  - npm install -g yarn

install:
  - git reset --hard HEAD
  - git submodule update --init --recursive
  - yarn

script:
  - yarn build
branches:
  only:
  - master
