osx_image: xcode8.3
sudo: required
dist: trusty
language: node_js
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang


node_js:
  - 'lts/*'
#  - '8'

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

before_install:
  - npm install -g yarn

install:
  - git reset --hard HEAD
  - git submodule update --init --recursive
  - yarn

script:
  - yarn build
branches:
  only:
  - master
